kind: Cluster
apiVersion: kubeadm.k8s.io/v1beta3
#apiVersion: kind.x-k8s.io/v1alpha4
name: ostad-cluster
nodes: 
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
      - containerPort: 30081
        hostPort: 30081
        
        